[package]
name = "nft_delegate"
edition = "2021"
version = "0.1.0"
license = "MIT"
description = "The Contract for NFT-721 Delegate platform"

[lib]
crate-type = ["cdylib"]


[dependencies]
near-sdk = "4.0.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
unidecode = "0.3.0"
